-- 2026 FIFA World Cup - All 48 team squads (1,248 players)
-- Source: Al Jazeera / FIFA official announcements, June 2 2026
-- Run this in Khal Bala's Supabase SQL Editor AFTER creating the kb_players table

INSERT INTO kb_players (name, team) VALUES
('Oussama Benbot', 'Algeria'),
('Melvin Masstil', 'Algeria'),
('Luca Zidane', 'Algeria'),
('Achraf Abada', 'Algeria'),
('Rayan Ait Nouri', 'Algeria'),
('Zinedine Belaid', 'Algeria'),
('Rafik Belghali', 'Algeria'),
('Ramy Bensebaini', 'Algeria'),
('Samir Chergui', 'Algeria'),
('Jaouen Hadjam', 'Algeria'),
('Aissa Mandi', 'Algeria'),
('Mohamed Amine Tougai', 'Algeria'),
('Houssem Aouar', 'Algeria'),
('Nabil Bentaleb', 'Algeria'),
('Hicham Boudaoui', 'Algeria'),
('Fares Chaibi', 'Algeria'),
('Ibrahim Maza', 'Algeria'),
('Yassine Titraoui', 'Algeria'),
('Ramiz Zerrouki', 'Algeria'),
('Mohamed Amine Amoura', 'Algeria'),
('Nadir Benbouali', 'Algeria'),
('Adil Boulbina', 'Algeria'),
('Fares Ghedjemis', 'Algeria'),
('Amine Gouiri', 'Algeria'),
('Riyad Mahrez', 'Algeria'),
('Anis Hadj Moussa', 'Algeria'),
('Emiliano Martinez', 'Argentina'),
('Geronimo Rulli', 'Argentina'),
('Juan Musso', 'Argentina'),
('Leonardo Balerdi', 'Argentina'),
('Gonzalo Montiel', 'Argentina'),
('Nicolas Tagliafico', 'Argentina'),
('Lisandro Martinez', 'Argentina'),
('Cristian Romero', 'Argentina'),
('Nicolas Otamendi', 'Argentina'),
('Facundo Medina', 'Argentina'),
('Nahuel Molina', 'Argentina'),
('Leandro Paredes', 'Argentina'),
('Rodrigo De Paul', 'Argentina'),
('Valentin Barco', 'Argentina'),
('Giovani Lo Celso', 'Argentina'),
('Exequiel Palacios', 'Argentina'),
('Alexis Mac Allister', 'Argentina'),
('Enzo Fernandez', 'Argentina'),
('Julian Alvarez', 'Argentina'),
('Lionel Messi', 'Argentina'),
('Nicolas Gonzalez', 'Argentina'),
('Thiago Almada', 'Argentina'),
('Giuliano Simeone', 'Argentina'),
('Nicolas Paz', 'Argentina'),
('Jose Manuel Lopez', 'Argentina'),
('Lautaro Martinez', 'Argentina'),
('Patrick Beach', 'Australia'),
('Paul Izzo', 'Australia'),
('Mathew Ryan', 'Australia'),
('Aziz Behich', 'Australia'),
('Jordan Bos', 'Australia'),
('Cameron Burgess', 'Australia'),
('Alessandro Circati', 'Australia'),
('Milos Degenek', 'Australia'),
('Jason Geria', 'Australia'),
('Lucas Herrington', 'Australia'),
('Jacob Italiano', 'Australia'),
('Harry Souttar', 'Australia'),
('Kai Trewin', 'Australia'),
('Cameron Devlin', 'Australia'),
('Ajdin Hrustic', 'Australia'),
('Jackson Irvine', 'Australia'),
('Connor Metcalfe', 'Australia'),
('Aiden O''Neill', 'Australia'),
('Paul Okon-Engstler', 'Australia'),
('Nestory Irankunda', 'Australia'),
('Mathew Leckie', 'Australia'),
('Awer Mabil', 'Australia'),
('Mohamed Toure', 'Australia'),
('Nishan Velupillay', 'Australia'),
('Cristian Volpato', 'Australia'),
('Tete Yengi', 'Australia'),
('Patrick Pentz', 'Austria'),
('Alexander Schlager', 'Austria'),
('Florian Wiegele', 'Austria'),
('David Affengruber', 'Austria'),
('David Alaba', 'Austria'),
('Kevin Danso', 'Austria'),
('Marco Friedl', 'Austria'),
('Philipp Lienhart', 'Austria'),
('Phillipp Mwene', 'Austria'),
('Stefan Posch', 'Austria'),
('Alexander Prass', 'Austria'),
('Michael Svoboda', 'Austria'),
('Christoph Baumgartner', 'Austria'),
('Carney Chukwuemeka', 'Austria'),
('Florian Grillitsch', 'Austria'),
('Konrad Laimer', 'Austria'),
('Marcel Sabitzer', 'Austria'),
('Xaver Schlager', 'Austria'),
('Romano Schmid', 'Austria'),
('Alessandro Schopf', 'Austria'),
('Nicolas Seiwald', 'Austria'),
('Paul Wanner', 'Austria'),
('Patrick Wimmer', 'Austria'),
('Marko Arnautovic', 'Austria'),
('Michael Gregoritsch', 'Austria'),
('Sasa Kalajdzic', 'Austria'),
('Thibaut Courtois', 'Belgium'),
('Senne Lammens', 'Belgium'),
('Mike Penders', 'Belgium'),
('Timothy Castagne', 'Belgium'),
('Zeno Debast', 'Belgium'),
('Maxim De Cuyper', 'Belgium'),
('Koni De Winter', 'Belgium'),
('Brandon Mechele', 'Belgium'),
('Thomas Meunier', 'Belgium'),
('Nathan Ngoy', 'Belgium'),
('Joaquin Seys', 'Belgium'),
('Arthur Theate', 'Belgium'),
('Kevin De Bruyne', 'Belgium'),
('Amadou Onana', 'Belgium'),
('Nicolas Raskin', 'Belgium'),
('Youri Tielemans', 'Belgium'),
('Hans Vanaken', 'Belgium'),
('Axel Witsel', 'Belgium'),
('Charles De Ketelaere', 'Belgium'),
('Jeremy Doku', 'Belgium'),
('Matias Fernandez-Pardo', 'Belgium'),
('Romelu Lukaku', 'Belgium'),
('Dodi Lukebakio', 'Belgium'),
('Diego Moreira', 'Belgium'),
('Alexis Saelemaekers', 'Belgium'),
('Leandro Trossard', 'Belgium'),
('Nikola Vasilj', 'Bosnia and Herzegovina'),
('Martin Zlomislic', 'Bosnia and Herzegovina'),
('Osman Hadzikic', 'Bosnia and Herzegovina'),
('Sead Kolasinac', 'Bosnia and Herzegovina'),
('Amar Dedic', 'Bosnia and Herzegovina'),
('Nihad Mujakic', 'Bosnia and Herzegovina'),
('Nikola Katic', 'Bosnia and Herzegovina'),
('Tarik Muharemovic', 'Bosnia and Herzegovina'),
('Stjepan Radeljic', 'Bosnia and Herzegovina'),
('Dennis Hadzikadunic', 'Bosnia and Herzegovina'),
('Nidal Celik', 'Bosnia and Herzegovina'),
('Amir Hadziahmetovic', 'Bosnia and Herzegovina'),
('Ivan Sunjic', 'Bosnia and Herzegovina'),
('Ivan Basic', 'Bosnia and Herzegovina'),
('Dzenis Burnic', 'Bosnia and Herzegovina'),
('Ermin Mahmic', 'Bosnia and Herzegovina'),
('Benjamin Tahirovic', 'Bosnia and Herzegovina'),
('Amar Memic', 'Bosnia and Herzegovina'),
('Armin Gigovic', 'Bosnia and Herzegovina'),
('Kerim Alajbegovic', 'Bosnia and Herzegovina'),
('Esmir Bajraktarevic', 'Bosnia and Herzegovina'),
('Ermedin Demirovic', 'Bosnia and Herzegovina'),
('Jovo Lukic', 'Bosnia and Herzegovina'),
('Samed Bazdar', 'Bosnia and Herzegovina'),
('Haris Tabakovic', 'Bosnia and Herzegovina'),
('Edin Dzeko', 'Bosnia and Herzegovina'),
('Alisson', 'Brazil'),
('Ederson', 'Brazil'),
('Weverton', 'Brazil'),
('Alex Sandro', 'Brazil'),
('Bremer', 'Brazil'),
('Danilo', 'Brazil'),
('Douglas Santos', 'Brazil'),
('Gabriel Magalhaes', 'Brazil'),
('Ibanez', 'Brazil'),
('Leo Pereira', 'Brazil'),
('Marquinhos', 'Brazil'),
('Wesley', 'Brazil'),
('Bruno Guimaraes', 'Brazil'),
('Casemiro', 'Brazil'),
('Danilo Santos', 'Brazil'),
('Fabinho', 'Brazil'),
('Lucas Paqueta', 'Brazil'),
('Endrick', 'Brazil'),
('Gabriel Martinelli', 'Brazil'),
('Igor Thiago', 'Brazil'),
('Luiz Henrique', 'Brazil'),
('Matheus Cunha', 'Brazil'),
('Neymar Jr', 'Brazil'),
('Raphinha', 'Brazil'),
('Rayan', 'Brazil'),
('Vinicius Jr', 'Brazil'),
('Dayne St Clair', 'Canada'),
('Maxime Crepeau', 'Canada'),
('Owen Goodman', 'Canada'),
('Alistair Johnston', 'Canada'),
('Derek Cornelius', 'Canada'),
('Richie Laryea', 'Canada'),
('Niko Sigur', 'Canada'),
('Joel Waterman', 'Canada'),
('Luc de Fougerolles', 'Canada'),
('Moise Bombito', 'Canada'),
('Alphonso Davies', 'Canada'),
('Alfie Jones', 'Canada'),
('Stephen Eustaquio', 'Canada'),
('Ismael Kone', 'Canada'),
('Tajon Buchanan', 'Canada'),
('Mathieu Choiniere', 'Canada'),
('Ali Ahmed', 'Canada'),
('Nathan Saliba', 'Canada'),
('Liam Millar', 'Canada'),
('Jacob Shaffelburg', 'Canada'),
('Jonathan Osorio', 'Canada'),
('Jonathan David', 'Canada'),
('Cyle Larin', 'Canada'),
('Tani Oluwaseyi', 'Canada'),
('Promise David', 'Canada'),
('CJ dos Santos', 'Cape Verde'),
('Marcio Rosa', 'Cape Verde'),
('Vozinha', 'Cape Verde'),
('Sidny Cabral', 'Cape Verde'),
('Diney Borges', 'Cape Verde'),
('Logan Costa', 'Cape Verde'),
('Roberto Lopes', 'Cape Verde'),
('Steven Moreira', 'Cape Verde'),
('Wagner Pina', 'Cape Verde'),
('Kelvin Pires', 'Cape Verde'),
('Joao Paulo Fernandes', 'Cape Verde'),
('Ianique Tavares', 'Cape Verde'),
('Telmo Arcanjo', 'Cape Verde'),
('Deroy Duarte', 'Cape Verde'),
('Laros Duarte', 'Cape Verde'),
('Jamiro Monteiro', 'Cape Verde'),
('Kevin Pina', 'Cape Verde'),
('Yannick Semedo', 'Cape Verde'),
('Gilson Benchimol', 'Cape Verde'),
('Jovane Cabral', 'Cape Verde'),
('Dailon Livramento', 'Cape Verde'),
('Ryan Mendes', 'Cape Verde'),
('Nuno da Costa', 'Cape Verde'),
('Garry Rodrigues', 'Cape Verde'),
('Willy Semedo', 'Cape Verde'),
('Helio Varela', 'Cape Verde'),
('Camilo Vargas', 'Colombia'),
('Alvaro Montero', 'Colombia'),
('David Ospina', 'Colombia'),
('Davinson Sanchez', 'Colombia'),
('Jhon Lucumi', 'Colombia'),
('Yerry Mina', 'Colombia'),
('Willer Ditta', 'Colombia'),
('Daniel Munoz', 'Colombia'),
('Santiago Arias', 'Colombia'),
('Johan Mojica', 'Colombia'),
('Deiver Machado', 'Colombia'),
('Richard Rios', 'Colombia'),
('Jefferson Lerma', 'Colombia'),
('Kevin Castano', 'Colombia'),
('Juan Camilo Portilla', 'Colombia'),
('Gustavo Puerta', 'Colombia'),
('Jhon Arias', 'Colombia'),
('Jorge Carrascal', 'Colombia'),
('Juan Fernando Quintero', 'Colombia'),
('James Rodriguez', 'Colombia'),
('Jaminton Campaz', 'Colombia'),
('Juan Camilo Hernandez', 'Colombia'),
('Luis Diaz', 'Colombia'),
('Luis Suarez', 'Colombia'),
('Carlos Gomez', 'Colombia'),
('Jhon Cordoba', 'Colombia'),
('Dominik Livakovic', 'Croatia'),
('Dominik Kotarski', 'Croatia'),
('Ivor Pandur', 'Croatia'),
('Josko Gvardiol', 'Croatia'),
('Duje Caleta-Car', 'Croatia'),
('Josip Sutalo', 'Croatia'),
('Josip Stanisic', 'Croatia'),
('Marin Pongracic', 'Croatia'),
('Martin Erlic', 'Croatia'),
('Luka Vuskovic', 'Croatia'),
('Luka Modric', 'Croatia'),
('Mateo Kovacic', 'Croatia'),
('Mario Pasalic', 'Croatia'),
('Nikola Vlasic', 'Croatia'),
('Luka Sucic', 'Croatia'),
('Martin Baturina', 'Croatia'),
('Kristijan Jakic', 'Croatia'),
('Petar Sucic', 'Croatia'),
('Nikola Moro', 'Croatia'),
('Toni Fruk', 'Croatia'),
('Ivan Perisic', 'Croatia'),
('Andrej Kramaric', 'Croatia'),
('Ante Budimir', 'Croatia'),
('Marco Pasalic', 'Croatia'),
('Petar Musa', 'Croatia'),
('Igor Matanovic', 'Croatia'),
('Tyrick Bodack', 'Curacao'),
('Trevor Doornbusch', 'Curacao'),
('Eloy Room', 'Curacao'),
('Riechedly Bazoer', 'Curacao'),
('Joshua Brenet', 'Curacao'),
('Roshon van Eijma', 'Curacao'),
('Sherel Floranus', 'Curacao'),
('Deveron Fonville', 'Curacao'),
('Jurien Gaari', 'Curacao'),
('Armando Obispo', 'Curacao'),
('Shurandy Sambo', 'Curacao'),
('Juninho Bacuna', 'Curacao'),
('Leandro Bacuna', 'Curacao'),
('Livano Comenencia', 'Curacao'),
('Kevin Felida', 'Curacao'),
('Arjany Martha', 'Curacao'),
('Tyrese Noslin', 'Curacao'),
('Godfried Roemeratoe', 'Curacao'),
('Jeremy Antonisse', 'Curacao'),
('Tahith Chong', 'Curacao'),
('Kenji Gorre', 'Curacao'),
('Sontje Hansen', 'Curacao'),
('Gervane Kastaneer', 'Curacao'),
('Brandley Kuwas', 'Curacao'),
('Jurgen Locadia', 'Curacao'),
('Jearl Margaritha', 'Curacao'),
('Lukas Hornicek', 'Czechia'),
('Matej Kovar', 'Czechia'),
('Jindrich Stanek', 'Czechia'),
('Vladimir Coufal', 'Czechia'),
('David Doudera', 'Czechia'),
('Tomas Holes', 'Czechia'),
('Robin Hranac', 'Czechia'),
('Stepan Chaloupek', 'Czechia'),
('David Jurasek', 'Czechia'),
('Ladislav Krejci', 'Czechia'),
('Jaroslav Zeleny', 'Czechia'),
('David Zima', 'Czechia'),
('Lukas Cerv', 'Czechia'),
('Vladimir Darida', 'Czechia'),
('Lukas Provod', 'Czechia'),
('Michal Sadilek', 'Czechia'),
('Hugo Sochurek', 'Czechia'),
('Alexandr Sojka', 'Czechia'),
('Tomas Soucek', 'Czechia'),
('Pavel Sulc', 'Czechia'),
('Denis Visinsky', 'Czechia'),
('Adam Hlozek', 'Czechia'),
('Tomas Chory', 'Czechia'),
('Mojmir Chytil', 'Czechia'),
('Jan Kuchta', 'Czechia'),
('Patrik Schick', 'Czechia'),
('Matthieu Epolo', 'DR Congo'),
('Timothy Fayulu', 'DR Congo'),
('Lionel Mpasi', 'DR Congo'),
('Dylan Batubinsika', 'DR Congo'),
('Gedeon Kalulu', 'DR Congo'),
('Steve Kapuadi', 'DR Congo'),
('Joris Kayembe', 'DR Congo'),
('Arthur Masuaku', 'DR Congo'),
('Chancel Mbemba', 'DR Congo'),
('Axel Tuanzebe', 'DR Congo'),
('Aaron Wan-Bissaka', 'DR Congo'),
('Brian Cipenga', 'DR Congo'),
('Meshack Elia', 'DR Congo'),
('Gael Kakuta', 'DR Congo'),
('Edo Kayembe', 'DR Congo'),
('Nathanael Mbuku', 'DR Congo'),
('Samuel Moutoussamy', 'DR Congo'),
('Ngalayel Mukau', 'DR Congo'),
('Charles Pickel', 'DR Congo'),
('Noah Sadiki', 'DR Congo'),
('Aaron Tshibola', 'DR Congo'),
('Cedric Bakambu', 'DR Congo'),
('Simon Banza', 'DR Congo'),
('Fiston Mayele', 'DR Congo'),
('Yoane Wissa', 'DR Congo'),
('Theo Bongonda', 'DR Congo'),
('Hernan Galindez', 'Ecuador'),
('Moises Ramirez', 'Ecuador'),
('Gonzalo Valle', 'Ecuador'),
('Piero Hincapie', 'Ecuador'),
('Willian Pacho', 'Ecuador'),
('Pervis Estupinan', 'Ecuador'),
('Felix Torres', 'Ecuador'),
('Joel Ordonez', 'Ecuador'),
('Jackson Porozo', 'Ecuador'),
('Angelo Preciado', 'Ecuador'),
('Yaimar Medina', 'Ecuador'),
('Moises Caicedo', 'Ecuador'),
('Alan Franco', 'Ecuador'),
('Kendry Paez', 'Ecuador'),
('Gonzalo Plata', 'Ecuador'),
('Pedro Vite', 'Ecuador'),
('Jordy Alcivar', 'Ecuador'),
('Denil Castillo', 'Ecuador'),
('John Yeboah', 'Ecuador'),
('Nilson Angulo', 'Ecuador'),
('Alan Minda', 'Ecuador'),
('Enner Valencia', 'Ecuador'),
('Kevin Rodriguez', 'Ecuador'),
('Jordy Caicedo', 'Ecuador'),
('Anthony Valencia', 'Ecuador'),
('Jeremy Arevalo', 'Ecuador'),
('Mohamed El Shenawy', 'Egypt'),
('Mostafa Shobeir', 'Egypt'),
('El Mahdy Soliman', 'Egypt'),
('Mohamed Alaa', 'Egypt'),
('Mohamed Abdelmonem', 'Egypt'),
('Mohamed Hany', 'Egypt'),
('Yasser Ibrahim', 'Egypt'),
('Hossam Abdelmaguid', 'Egypt'),
('Ahmed Fattouh', 'Egypt'),
('Tarek Alaa', 'Egypt'),
('Rami Rabia', 'Egypt'),
('Karim Hafez', 'Egypt'),
('Marwan Attia', 'Egypt'),
('Ahmed Sayed Zizo', 'Egypt'),
('Mahmoud Hassan Trezeguet', 'Egypt'),
('Emam Ashour', 'Egypt'),
('Mostafa Abdel Raouf', 'Egypt'),
('Mohannad Lasheen', 'Egypt'),
('Haitham Hassan', 'Egypt'),
('Mahmoud Saber', 'Egypt'),
('Ibrahim Adel', 'Egypt'),
('Nabil Emad', 'Egypt'),
('Hamdi Fathi', 'Egypt'),
('Mohamed Salah', 'Egypt'),
('Omar Marmoush', 'Egypt'),
('Hamza Abdel Karim', 'Egypt'),
('Jordan Pickford', 'England'),
('Dean Henderson', 'England'),
('James Trafford', 'England'),
('Reece James', 'England'),
('Ezri Konsa', 'England'),
('Jarell Quansah', 'England'),
('John Stones', 'England'),
('Marc Guehi', 'England'),
('Dan Burn', 'England'),
('Nico O''Reilly', 'England'),
('Djed Spence', 'England'),
('Tino Livramento', 'England'),
('Declan Rice', 'England'),
('Elliot Anderson', 'England'),
('Kobbie Mainoo', 'England'),
('Jordan Henderson', 'England'),
('Morgan Rogers', 'England'),
('Jude Bellingham', 'England'),
('Eberechi Eze', 'England'),
('Harry Kane', 'England'),
('Ivan Toney', 'England'),
('Ollie Watkins', 'England'),
('Bukayo Saka', 'England'),
('Marcus Rashford', 'England'),
('Anthony Gordon', 'England'),
('Noni Madueke', 'England'),
('Mike Maignan', 'France'),
('Robin Risser', 'France'),
('Brice Samba', 'France'),
('Lucas Digne', 'France'),
('Malo Gusto', 'France'),
('Lucas Hernandez', 'France'),
('Theo Hernandez', 'France'),
('Ibrahima Konate', 'France'),
('Maxence Lacroix', 'France'),
('Jules Kounde', 'France'),
('William Saliba', 'France'),
('Dayot Upamecano', 'France'),
('N''Golo Kante', 'France'),
('Manu Kone', 'France'),
('Adrien Rabiot', 'France'),
('Aurelien Tchouameni', 'France'),
('Warren Zaire-Emery', 'France'),
('Maghnes Akliouche', 'France'),
('Bradley Barcola', 'France'),
('Rayan Cherki', 'France'),
('Ousmane Dembele', 'France'),
('Desire Doue', 'France'),
('Michael Olise', 'France'),
('Kylian Mbappe', 'France'),
('Jean-Philippe Mateta', 'France'),
('Marcus Thuram', 'France'),
('Manuel Neuer', 'Germany'),
('Oliver Baumann', 'Germany'),
('Alexander Nuebel', 'Germany'),
('Nico Schlotterbeck', 'Germany'),
('David Raum', 'Germany'),
('Nathaniel Brown', 'Germany'),
('Jonathan Tah', 'Germany'),
('Waldemar Anton', 'Germany'),
('Joshua Kimmich', 'Germany'),
('Malick Thiaw', 'Germany'),
('Antonio Rudiger', 'Germany'),
('Pascal Gross', 'Germany'),
('Leon Goretzka', 'Germany'),
('Felix Nmecha', 'Germany'),
('Jamal Musiala', 'Germany'),
('Nadiem Amiri', 'Germany'),
('Jamie Leweling', 'Germany'),
('Lennart Karl', 'Germany'),
('Florian Wirtz', 'Germany'),
('Leroy Sane', 'Germany'),
('Aleksandar Pavlovic', 'Germany'),
('Angelo Stiller', 'Germany'),
('Kai Havertz', 'Germany'),
('Nick Woltemade', 'Germany'),
('Deniz Undav', 'Germany'),
('Maximilian Beier', 'Germany'),
('Joseph Anang', 'Ghana'),
('Benjamin Asare', 'Ghana'),
('Lawrence Ati-Zigi', 'Ghana'),
('Jonas Adjetey', 'Ghana'),
('Derrick Luckassen', 'Ghana'),
('Gideon Mensah', 'Ghana'),
('Abdul Mumin', 'Ghana'),
('Jerome Opoku', 'Ghana'),
('Kojo Oppong Preprah', 'Ghana'),
('Baba Abdul Rahman', 'Ghana'),
('Alidu Seidu', 'Ghana'),
('Marvin Senaya', 'Ghana'),
('Augustine Boakye', 'Ghana'),
('Abdul Fatawu Issahaku', 'Ghana'),
('Elisha Owusu', 'Ghana'),
('Thomas Partey', 'Ghana'),
('Kwasi Sibo', 'Ghana'),
('Kamal Deen Sulemana', 'Ghana'),
('Caleb Yirenkyi', 'Ghana'),
('Prince Kwabena Adu', 'Ghana'),
('Jordan Ayew', 'Ghana'),
('Christopher Bonsu Baah', 'Ghana'),
('Ernest Nuamah', 'Ghana'),
('Antoine Semenyo', 'Ghana'),
('Brandon Thomas-Asante', 'Ghana'),
('Inaki Williams', 'Ghana'),
('Josue Duverger', 'Haiti'),
('Alexandre Pierre', 'Haiti'),
('Johny Placide', 'Haiti'),
('Ricardo Ade', 'Haiti'),
('Carlens Arcus', 'Haiti'),
('Hannes Delcroix', 'Haiti'),
('Jean-Kevin Duverne', 'Haiti'),
('Martin Experience', 'Haiti'),
('Duke Lacroix', 'Haiti'),
('Wilguens Paugain', 'Haiti'),
('Keeto Thermoncy', 'Haiti'),
('Carl Fred Sainte', 'Haiti'),
('Jean-Ricner Bellegarde', 'Haiti'),
('Leverton Pierre', 'Haiti'),
('Danley Jean Jacques', 'Haiti'),
('Woodensky Pierre', 'Haiti'),
('Dominique Simon', 'Haiti'),
('Josue Casimir', 'Haiti'),
('Louicius Deedson', 'Haiti'),
('Derrick Etienne Jr.', 'Haiti'),
('Yassin Fortune', 'Haiti'),
('Wilson Isidor', 'Haiti'),
('Lenny Joseph', 'Haiti'),
('Duckens Nazon', 'Haiti'),
('Frantzdy Pierrot', 'Haiti'),
('Ruben Providence', 'Haiti'),
('Alireza Beiranvand', 'Iran'),
('Seyed Hossein Hosseini', 'Iran'),
('Payam Niazmand', 'Iran'),
('Danial Eiri', 'Iran'),
('Ehsan Hajsafi', 'Iran'),
('Saleh Hardani', 'Iran'),
('Hossein Kanaani', 'Iran'),
('Shoja Khalilzadeh', 'Iran'),
('Milad Mohammadi', 'Iran'),
('Ali Nemati', 'Iran'),
('Ramin Rezaeian', 'Iran'),
('Rouzbeh Cheshmi', 'Iran'),
('Saeid Ezatolahi', 'Iran'),
('Mehdi Ghaedi', 'Iran'),
('Saman Ghoddos', 'Iran'),
('Mohammad Ghorbani', 'Iran'),
('Alireza Jahanbakhsh', 'Iran'),
('Mohammad Mohebi', 'Iran'),
('Amir Mohammad Razzaghinia', 'Iran'),
('Mehdi Torabi', 'Iran'),
('Aria Yousefi', 'Iran'),
('Ali Alipour', 'Iran'),
('Dennis Dargahi', 'Iran'),
('Amirhossein Hosseinzadeh', 'Iran'),
('Mehdi Taremi', 'Iran'),
('Shahriar Moghanlou', 'Iran'),
('Fahad Talib', 'Iraq'),
('Jalal Hassan', 'Iraq'),
('Ahmed Basil', 'Iraq'),
('Hussein Ali', 'Iraq'),
('Manaf Younis', 'Iraq'),
('Zaid Tahseen', 'Iraq'),
('Rebin Sulaka', 'Iraq'),
('Akam Hashem', 'Iraq'),
('Merchas Doski', 'Iraq'),
('Ahmed Yahya', 'Iraq'),
('Zaid Ismail', 'Iraq'),
('Frans Putros', 'Iraq'),
('Mustafa Saadoon', 'Iraq'),
('Amir Al Ammari', 'Iraq'),
('Kevin Yakob', 'Iraq'),
('Zidane Iqbal', 'Iraq'),
('Aimar Sher', 'Iraq'),
('Ibrahim Bayesh', 'Iraq'),
('Ahmed Qasim', 'Iraq'),
('Youssef Amyn', 'Iraq'),
('Marko Farji', 'Iraq'),
('Ali Jassim', 'Iraq'),
('Ali Al Hamadi', 'Iraq'),
('Ali Yousef', 'Iraq'),
('Aymen Hussein', 'Iraq'),
('Mohanad Ali', 'Iraq'),
('Yahia Fofana', 'Ivory Coast'),
('Mohamed Kone', 'Ivory Coast'),
('Alban Lafont', 'Ivory Coast'),
('Emmanuel Agbadou', 'Ivory Coast'),
('Christopher Operi', 'Ivory Coast'),
('Ousmane Diomande', 'Ivory Coast'),
('Guela Doue', 'Ivory Coast'),
('Ghislain Konan', 'Ivory Coast'),
('Odilon Kossounou', 'Ivory Coast'),
('Wilfried Singo', 'Ivory Coast'),
('Evan Ndicka', 'Ivory Coast'),
('Seko Fofana', 'Ivory Coast'),
('Parfait Guiagon', 'Ivory Coast'),
('Christ Inao Oulai', 'Ivory Coast'),
('Franck Kessie', 'Ivory Coast'),
('Ibrahim Sangare', 'Ivory Coast'),
('Jean Michael Seri', 'Ivory Coast'),
('Simon Adingra', 'Ivory Coast'),
('Ange-Yoan Bonny', 'Ivory Coast'),
('Amad Diallo', 'Ivory Coast'),
('Oumar Diakite', 'Ivory Coast'),
('Yan Diomande', 'Ivory Coast'),
('Evann Guessand', 'Ivory Coast'),
('Nicolas Pepe', 'Ivory Coast'),
('Bazoumana Toure', 'Ivory Coast'),
('Elye Wahi', 'Ivory Coast'),
('Tomoki Hayakawa', 'Japan'),
('Keisuke Osako', 'Japan'),
('Zion Suzuki', 'Japan'),
('Ko Itakura', 'Japan'),
('Hiroki Ito', 'Japan'),
('Yuto Nagatomo', 'Japan'),
('Ayumu Seko', 'Japan'),
('Yukinari Sugawara', 'Japan'),
('Junnosuke Suzuki', 'Japan'),
('Shogo Taniguchi', 'Japan'),
('Takehiro Tomiyasu', 'Japan'),
('Tsuyoshi Watanabe', 'Japan'),
('Ritsu Doan', 'Japan'),
('Wataru Endo', 'Japan'),
('Junya Ito', 'Japan'),
('Daichi Kamada', 'Japan'),
('Takefusa Kubo', 'Japan'),
('Keito Nakamura', 'Japan'),
('Kaishu Sano', 'Japan'),
('Ao Tanaka', 'Japan'),
('Keisuke Goto', 'Japan'),
('Daizen Maeda', 'Japan'),
('Koki Ogawa', 'Japan'),
('Kento Shiogai', 'Japan'),
('Yuito Suzuki', 'Japan'),
('Ayase Ueda', 'Japan'),
('Yazid Abulaila', 'Jordan'),
('Noor Bani Attiah', 'Jordan'),
('Abdallah Al Fakhouri', 'Jordan'),
('Mohammad Abu Hashish', 'Jordan'),
('Abdullah Nasib', 'Jordan'),
('Hussam Abu Dhahab', 'Jordan'),
('Yazan Al Arab', 'Jordan'),
('Mohammad Abu Alnadi', 'Jordan'),
('Salem Obaid', 'Jordan'),
('Saed Al Rosan', 'Jordan'),
('Ehsan Haddad', 'Jordan'),
('Anas Badawi', 'Jordan'),
('Amer Jamous', 'Jordan'),
('Noor Al Rawabdeh', 'Jordan'),
('Rajaei Ayed', 'Jordan'),
('Ibrahim Sadeh', 'Jordan'),
('Mohannad Abu Taha', 'Jordan'),
('Nizar Al Rashdan', 'Jordan'),
('Mohammad Al Dawoud', 'Jordan'),
('Mahmoud Mardahi', 'Jordan'),
('Mohammad Abu Zraiq', 'Jordan'),
('Ali Olwan', 'Jordan'),
('Mousa Al Tamari', 'Jordan'),
('Odeh Fakhoury', 'Jordan'),
('Ibrahim Sabra', 'Jordan'),
('Ali Azaizeh', 'Jordan'),
('Raul Rangel', 'Mexico'),
('Guillermo Ochoa', 'Mexico'),
('Carlos Acevedo', 'Mexico'),
('Jorge Sanchez', 'Mexico'),
('Israel Reyes', 'Mexico'),
('Cesar Montes', 'Mexico'),
('Johan Vasquez', 'Mexico'),
('Jesus Gallardo', 'Mexico'),
('Mateo Chavez', 'Mexico'),
('Edson Alvarez', 'Mexico'),
('Erik Lira', 'Mexico'),
('Orbelin Pineda', 'Mexico'),
('Alvaro Fidalgo', 'Mexico'),
('Brian Gutierrez', 'Mexico'),
('Luis Romo', 'Mexico'),
('Obed Vargas', 'Mexico'),
('Gilberto Mora', 'Mexico'),
('Luis Chavez', 'Mexico'),
('Roberto Alvarado', 'Mexico'),
('Cesar Huerta', 'Mexico'),
('Alexis Vega', 'Mexico'),
('Julian Quinones', 'Mexico'),
('Guillermo Martinez', 'Mexico'),
('Armando Gonzalez', 'Mexico'),
('Santiago Gimenez', 'Mexico'),
('Raul Jimenez', 'Mexico'),
('Yassine Bounou', 'Morocco'),
('Munir El Kajoui', 'Morocco'),
('Ahmed Reda Tagnaouti', 'Morocco'),
('Noussair Mazraoui', 'Morocco'),
('Anas Salah-Eddine', 'Morocco'),
('Youssef Bellammari', 'Morocco'),
('Achraf Hakimi', 'Morocco'),
('Zakaria El Ouahdi', 'Morocco'),
('Nayef Aguerd', 'Morocco'),
('Chadi Riad', 'Morocco'),
('Redouane Halhal', 'Morocco'),
('Issa Diop', 'Morocco'),
('Samir El Mourabet', 'Morocco'),
('Ayoub Bouaddi', 'Morocco'),
('Neil El Aynaoui', 'Morocco'),
('Sofyan Amrabat', 'Morocco'),
('Azzedine Ounahi', 'Morocco'),
('Bilal El Khannouss', 'Morocco'),
('Ismael Saibari', 'Morocco'),
('Abdesamad Ezzalzouli', 'Morocco'),
('Chemsdine Talbi', 'Morocco'),
('Soufiane Rahimi', 'Morocco'),
('Ayoub El Kaabi', 'Morocco'),
('Brahim Diaz', 'Morocco'),
('Yassine Gessim', 'Morocco'),
('Ayoube Amaimouni-Echghouyab', 'Morocco'),
('Mark Flekken', 'Netherlands'),
('Robin Roefs', 'Netherlands'),
('Bart Verbruggen', 'Netherlands'),
('Nathan Ake', 'Netherlands'),
('Virgil van Dijk', 'Netherlands'),
('Denzel Dumfries', 'Netherlands'),
('Jan Paul van Hecke', 'Netherlands'),
('Jurrien Timber', 'Netherlands'),
('Jorrel Hato', 'Netherlands'),
('Micky van de Ven', 'Netherlands'),
('Ryan Gravenberch', 'Netherlands'),
('Frenkie de Jong', 'Netherlands'),
('Teun Koopmeiners', 'Netherlands'),
('Tijjani Reijnders', 'Netherlands'),
('Marten de Roon', 'Netherlands'),
('Guus Til', 'Netherlands'),
('Quinten Timber', 'Netherlands'),
('Mats Wieffer', 'Netherlands'),
('Brian Brobbey', 'Netherlands'),
('Memphis Depay', 'Netherlands'),
('Cody Gakpo', 'Netherlands'),
('Noa Lang', 'Netherlands'),
('Donyell Malen', 'Netherlands'),
('Crysencio Summerville', 'Netherlands'),
('Wout Weghorst', 'Netherlands'),
('Justin Kluivert', 'Netherlands'),
('Max Crocombe', 'New Zealand'),
('Alex Paulsen', 'New Zealand'),
('Michael Woud', 'New Zealand'),
('Tyler Bindon', 'New Zealand'),
('Michael Boxall', 'New Zealand'),
('Liberato Cacace', 'New Zealand'),
('Francis de Vries', 'New Zealand'),
('Callan Elliot', 'New Zealand'),
('Tim Payne', 'New Zealand'),
('Nando Pijnaker', 'New Zealand'),
('Tommy Smith', 'New Zealand'),
('Finn Surman', 'New Zealand'),
('Lachlan Bayliss', 'New Zealand'),
('Joe Bell', 'New Zealand'),
('Matt Garbett', 'New Zealand'),
('Eli Just', 'New Zealand'),
('Callum McCowatt', 'New Zealand'),
('Ben Old', 'New Zealand'),
('Alex Rufer', 'New Zealand'),
('Marko Stamenic', 'New Zealand'),
('Sarpreet Singh', 'New Zealand'),
('Ryan Thomas', 'New Zealand'),
('Kosta Barbarouses', 'New Zealand'),
('Jesse Randall', 'New Zealand'),
('Ben Waine', 'New Zealand'),
('Chris Wood', 'New Zealand'),
('Orjan Haskjold Nyland', 'Norway'),
('Egil Selvik', 'Norway'),
('Sander Tangvik', 'Norway'),
('Kristoffer Vassbakk Ajer', 'Norway'),
('Fredrik Bjorkan', 'Norway'),
('Henrik Falchener', 'Norway'),
('Sondre Langas', 'Norway'),
('Torbjorn Heggem', 'Norway'),
('Marcus Holmgren Pedersen', 'Norway'),
('Julian Ryerson', 'Norway'),
('David Moller Wolfe', 'Norway'),
('Leo Ostigard', 'Norway'),
('Thelonious Aasgaard', 'Norway'),
('Fredrik Aursnes', 'Norway'),
('Patrick Berg', 'Norway'),
('Sander Berge', 'Norway'),
('Oscar Bobb', 'Norway'),
('Jens Petter Hauge', 'Norway'),
('Antonio Nusa', 'Norway'),
('Andreas Schjelderup', 'Norway'),
('Morten Thorsby', 'Norway'),
('Kristian Thorstvedt', 'Norway'),
('Martin Odegaard', 'Norway'),
('Erling Haaland', 'Norway'),
('Alexander Sorloth', 'Norway'),
('Jorgen Strand Larsen', 'Norway'),
('Orlando Mosquera', 'Panama'),
('Luis Mejia', 'Panama'),
('Cesar Samudio', 'Panama'),
('Cesar Blackman', 'Panama'),
('Jorge Gutierrez', 'Panama'),
('Amir Murillo', 'Panama'),
('Fidel Escobar', 'Panama'),
('Andres Andrade', 'Panama'),
('Edgardo Farina', 'Panama'),
('Jose Cordoba', 'Panama'),
('Eric Davis', 'Panama'),
('Jiovany Ramos', 'Panama'),
('Roderick Miller', 'Panama'),
('Anibal Godoy', 'Panama'),
('Adalberto Carrasquilla', 'Panama'),
('Carlos Harvey', 'Panama'),
('Cristian Martinez', 'Panama'),
('Jose Luis Rodriguez', 'Panama'),
('Cesar Yanis', 'Panama'),
('Yoel Barcenas', 'Panama'),
('Alberto Quintero', 'Panama'),
('Azarias Londono', 'Panama'),
('Ismael Diaz', 'Panama'),
('Cecilio Waterman', 'Panama'),
('Jose Fajardo', 'Panama'),
('Tomas Rodriguez', 'Panama'),
('Orlando Gill', 'Paraguay'),
('Roberto Fernandez', 'Paraguay'),
('Gaston Olveira', 'Paraguay'),
('Juan Caceres', 'Paraguay'),
('Gustavo Velazquez', 'Paraguay'),
('Gustavo Gomez', 'Paraguay'),
('Junior Alonso', 'Paraguay'),
('Jose Canale', 'Paraguay'),
('Omar Alderete', 'Paraguay'),
('Alexandro Maidana', 'Paraguay'),
('Fabian Balbuena', 'Paraguay'),
('Diego Gomez', 'Paraguay'),
('Mauricio Magalhaes', 'Paraguay'),
('Damian Bobadilla', 'Paraguay'),
('Braian Ojeda', 'Paraguay'),
('Andres Cubas', 'Paraguay'),
('Matias Galarza', 'Paraguay'),
('Alejandro Gamarra', 'Paraguay'),
('Gustavo Caballero', 'Paraguay'),
('Ramon Sosa', 'Paraguay'),
('Alex Arce', 'Paraguay'),
('Isidro Pitta', 'Paraguay'),
('Gabriel Avalos', 'Paraguay'),
('Miguel Almiron', 'Paraguay'),
('Julio Enciso', 'Paraguay'),
('Antonio Sanabria', 'Paraguay'),
('Diogo Costa', 'Portugal'),
('Jose Sa', 'Portugal'),
('Rui Silva', 'Portugal'),
('Tomas Araujo', 'Portugal'),
('Joao Cancelo', 'Portugal'),
('Diogo Dalot', 'Portugal'),
('Ruben Dias', 'Portugal'),
('Goncalo Inacio', 'Portugal'),
('Nuno Mendes', 'Portugal'),
('Matheus Nunes', 'Portugal'),
('Nelson Semedo', 'Portugal'),
('Renato Veiga', 'Portugal'),
('Samuel Costa', 'Portugal'),
('Bruno Fernandes', 'Portugal'),
('Joao Neves', 'Portugal'),
('Ruben Neves', 'Portugal'),
('Bernardo Silva', 'Portugal'),
('Vitinha', 'Portugal'),
('Francisco Conceicao', 'Portugal'),
('Joao Felix', 'Portugal'),
('Goncalo Guedes', 'Portugal'),
('Rafael Leao', 'Portugal'),
('Pedro Neto', 'Portugal'),
('Goncalo Ramos', 'Portugal'),
('Cristiano Ronaldo', 'Portugal'),
('Francisco Trincao', 'Portugal'),
('Salah Zakaria', 'Qatar'),
('Meshaal Barsham', 'Qatar'),
('Mahmoud Abunada', 'Qatar'),
('Boualem Khoukhi', 'Qatar'),
('Pedro Miguel', 'Qatar'),
('Sultan Al Brake', 'Qatar'),
('Al Hashmi Al Hussain', 'Qatar'),
('Ayoub Al Alawi', 'Qatar'),
('Issa Laye', 'Qatar'),
('Lucas Mendes', 'Qatar'),
('Homam Al Amin', 'Qatar'),
('Ahmed Fathi', 'Qatar'),
('Jassim Gaber', 'Qatar'),
('Assim Madibo', 'Qatar'),
('Abdulaziz Hatem', 'Qatar'),
('Karim Boudiaf', 'Qatar'),
('Mohammed Mannai', 'Qatar'),
('Almoez Ali', 'Qatar'),
('Akram Afif', 'Qatar'),
('Tahsin Mohammed', 'Qatar'),
('Edmilson Junior', 'Qatar'),
('Ahmed Al-Janehi', 'Qatar'),
('Ahmed Alaa', 'Qatar'),
('Hassan Al Haydos', 'Qatar'),
('Mohammed Muntari', 'Qatar'),
('Yusuf Abdurisag', 'Qatar'),
('Nawaf Al Aqidi', 'Saudi Arabia'),
('Mohamed Al Owais', 'Saudi Arabia'),
('Ahmed Alkassar', 'Saudi Arabia'),
('Saud Abdulhamid', 'Saudi Arabia'),
('Jehad Thakri', 'Saudi Arabia'),
('Abdulelah Al Amri', 'Saudi Arabia'),
('Hassan Tambakti', 'Saudi Arabia'),
('Ali Lajami', 'Saudi Arabia'),
('Hassan Kadesh', 'Saudi Arabia'),
('Moteb Al Harbi', 'Saudi Arabia'),
('Nawaf Boushal', 'Saudi Arabia'),
('Ali Majrashi', 'Saudi Arabia'),
('Mohammed Abu Alshamat', 'Saudi Arabia'),
('Ziyad Al Johani', 'Saudi Arabia'),
('Nasser Al Dawsari', 'Saudi Arabia'),
('Mohamed Kanno', 'Saudi Arabia'),
('Abdullah Al Khaibari', 'Saudi Arabia'),
('Alaa Al Hejji', 'Saudi Arabia'),
('Musab Al Juwayr', 'Saudi Arabia'),
('Sultan Mandash', 'Saudi Arabia'),
('Ayman Yahya', 'Saudi Arabia'),
('Khalid Al Ghannam', 'Saudi Arabia'),
('Salem Al Dawsari', 'Saudi Arabia'),
('Abdullah Al Hamdan', 'Saudi Arabia'),
('Feras Al Brikan', 'Saudi Arabia'),
('Saleh Al Shehri', 'Saudi Arabia'),
('Craig Gordon', 'Scotland'),
('Angus Gunn', 'Scotland'),
('Liam Kelly', 'Scotland'),
('Grant Hanley', 'Scotland'),
('Jack Hendry', 'Scotland'),
('Aaron Hickey', 'Scotland'),
('Dom Hyam', 'Scotland'),
('Scott McKenna', 'Scotland'),
('Nathan Patterson', 'Scotland'),
('Anthony Ralston', 'Scotland'),
('Andy Robertson', 'Scotland'),
('John Souttar', 'Scotland'),
('Kieran Tierney', 'Scotland'),
('Ryan Christie', 'Scotland'),
('Findlay Curtis', 'Scotland'),
('Lewis Ferguson', 'Scotland'),
('Tyler Fletcher', 'Scotland'),
('Ben Gannon-Doak', 'Scotland'),
('John McGinn', 'Scotland'),
('Kenny McLean', 'Scotland'),
('Scott McTominay', 'Scotland'),
('Che Adams', 'Scotland'),
('Lyndon Dykes', 'Scotland'),
('George Hirst', 'Scotland'),
('Lawrence Shankland', 'Scotland'),
('Ross Stewart', 'Scotland'),
('Edouard Mendy', 'Senegal'),
('Mory Diaw', 'Senegal'),
('Yehvann Diouf', 'Senegal'),
('Krepin Diatta', 'Senegal'),
('Antoine Mendy', 'Senegal'),
('Kalidou Koulibaly', 'Senegal'),
('El Hadji Malick Diouf', 'Senegal'),
('Mamadou Sarr', 'Senegal'),
('Moussa Niakhate', 'Senegal'),
('Abdoulaye Seck', 'Senegal'),
('Ismail Jakobs', 'Senegal'),
('Idrissa Gana Gueye', 'Senegal'),
('Pape Gueye', 'Senegal'),
('Lamine Camara', 'Senegal'),
('Habib Diarra', 'Senegal'),
('Pathe Ciss', 'Senegal'),
('Pape Matar Sarr', 'Senegal'),
('Bara Sapoko Ndiaye', 'Senegal'),
('Sadio Mane', 'Senegal'),
('Ismaila Sarr', 'Senegal'),
('Iliman Ndiaye', 'Senegal'),
('Assane Diao', 'Senegal'),
('Ibrahim Mbaye', 'Senegal'),
('Nicolas Jackson', 'Senegal'),
('Bamba Dieng', 'Senegal'),
('Cherif Ndiaye', 'Senegal'),
('Ronwen Williams', 'South Africa'),
('Ricardo Goss', 'South Africa'),
('Sipho Chaine', 'South Africa'),
('Aubrey Modiba', 'South Africa'),
('Khuliso Mudau', 'South Africa'),
('Khulumani Ndamane', 'South Africa'),
('Kamogelo Sebelebele', 'South Africa'),
('Nkosinathi Sibisi', 'South Africa'),
('Bradley Cross', 'South Africa'),
('Samukele Kabini', 'South Africa'),
('Olwethu Makhanya', 'South Africa'),
('Thabang Matuludi', 'South Africa'),
('Mbekezeli Mbokazi', 'South Africa'),
('Ime Okon', 'South Africa'),
('Oswin Appollis', 'South Africa'),
('Thalente Mbatha', 'South Africa'),
('Relebohile Mofokeng', 'South Africa'),
('Jayden Adams', 'South Africa'),
('Teboho Mokoena', 'South Africa'),
('Themba Zwane', 'South Africa'),
('Sphephelo Sithole', 'South Africa'),
('Evidence Makgopa', 'South Africa'),
('Tshepang Moremi', 'South Africa'),
('Lyle Foster', 'South Africa'),
('Thapelo Maseko', 'South Africa'),
('Iqraam Rayners', 'South Africa'),
('Song Bumkeun', 'South Korea'),
('Jo Hyeonwoo', 'South Korea'),
('Kim Seung-gyu', 'South Korea'),
('Jens Castrop', 'South Korea'),
('Lee Hanbeom', 'South Korea'),
('Park Jinseob', 'South Korea'),
('Lee Kihyuk', 'South Korea'),
('Kim Minjae', 'South Korea'),
('Kim Moonhwan', 'South Korea'),
('Kim Taehyeon', 'South Korea'),
('Lee Taeseok', 'South Korea'),
('Seol Youngwoo', 'South Korea'),
('Cho Wije', 'South Korea'),
('Lee Donggyeong', 'South Korea'),
('Hwang Heechan', 'South Korea'),
('Yang Hyunjun', 'South Korea'),
('Hwang Inbeom', 'South Korea'),
('Lee Jaesung', 'South Korea'),
('Kim Jingyu', 'South Korea'),
('Eom Jisung', 'South Korea'),
('Bae Junho', 'South Korea'),
('Lee Kangin', 'South Korea'),
('Paik Seungho', 'South Korea'),
('Cho Guesung', 'South Korea'),
('Son Heungmin', 'South Korea'),
('Oh Hyeongyu', 'South Korea'),
('Unai Simon', 'Spain'),
('David Raya', 'Spain'),
('Joan Garcia', 'Spain'),
('Marc Cucurella', 'Spain'),
('Pau Cubarsi', 'Spain'),
('Aymeric Laporte', 'Spain'),
('Alejandro Grimaldo', 'Spain'),
('Pedro Porro', 'Spain'),
('Eric Garcia', 'Spain'),
('Marcos Llorente', 'Spain'),
('Marc Pubill', 'Spain'),
('Gavi', 'Spain'),
('Rodri', 'Spain'),
('Pedri', 'Spain'),
('Martin Zubimendi', 'Spain'),
('Fabian Ruiz', 'Spain'),
('Alex Baena', 'Spain'),
('Mikel Merino', 'Spain'),
('Lamine Yamal', 'Spain'),
('Nico Williams', 'Spain'),
('Dani Olmo', 'Spain'),
('Ferran Torres', 'Spain'),
('Mikel Oyarzabal', 'Spain'),
('Yeremy Pino', 'Spain'),
('Borja Iglesias', 'Spain'),
('Victor Munoz', 'Spain'),
('Viktor Johansson', 'Sweden'),
('Gustaf Lagerbielke', 'Sweden'),
('Kristoffer Nordfeldt', 'Sweden'),
('Jacob Zetterstrom', 'Sweden'),
('Hjalmar Ekdal', 'Sweden'),
('Gabriel Gudmundsson', 'Sweden'),
('Isak Hien', 'Sweden'),
('Victor Lindelof', 'Sweden'),
('Eric Smith', 'Sweden'),
('Carl Starfelt', 'Sweden'),
('Daniel Svensson', 'Sweden'),
('Yasin Ayari', 'Sweden'),
('Lucas Bergvall', 'Sweden'),
('Jesper Karlstrom', 'Sweden'),
('Benjamin Nygren', 'Sweden'),
('Ken Sema', 'Sweden'),
('Elliot Stroud', 'Sweden'),
('Mattias Svanberg', 'Sweden'),
('Besfort Zeneli', 'Sweden'),
('Taha Ali', 'Sweden'),
('Alexander Bernhardsson', 'Sweden'),
('Anthony Elanga', 'Sweden'),
('Viktor Gyokeres', 'Sweden'),
('Alexander Isak', 'Sweden'),
('Gustaf Nilsson', 'Sweden'),
('Marvin Keller', 'Switzerland'),
('Gregor Kobel', 'Switzerland'),
('Yvon Mvogo', 'Switzerland'),
('Manuel Akanji', 'Switzerland'),
('Aurele Amenda', 'Switzerland'),
('Eray Comert', 'Switzerland'),
('Nico Elvedi', 'Switzerland'),
('Luca Jaquez', 'Switzerland'),
('Miro Muheim', 'Switzerland'),
('Ricardo Rodriguez', 'Switzerland'),
('Silvan Widmer', 'Switzerland'),
('Michel Aebischer', 'Switzerland'),
('Christian Fassnacht', 'Switzerland'),
('Remo Freuler', 'Switzerland'),
('Ardon Jashari', 'Switzerland'),
('Fabian Rieder', 'Switzerland'),
('Djibril Sow', 'Switzerland'),
('Cedric Itten', 'Switzerland'),
('Granit Xhaka', 'Switzerland'),
('Denis Zakaria', 'Switzerland'),
('Ruben Vargas', 'Switzerland'),
('Zeki Amdouni', 'Switzerland'),
('Breel Embolo', 'Switzerland'),
('Dan Ndoye', 'Switzerland'),
('Noah Okafor', 'Switzerland'),
('Johan Manzambi', 'Switzerland'),
('Sabri Ben Hessen', 'Tunisia'),
('Abdelmouhib Chamakh', 'Tunisia'),
('Aymen Dahman', 'Tunisia'),
('Ali Abdi', 'Tunisia'),
('Adem Arous', 'Tunisia'),
('Mohamed Amine Ben Hamida', 'Tunisia'),
('Dylan Bronn', 'Tunisia'),
('Raed Chikhaoui', 'Tunisia'),
('Moutaz Neffati', 'Tunisia'),
('Omar Rekik', 'Tunisia'),
('Montassar Talbi', 'Tunisia'),
('Yan Valery', 'Tunisia'),
('Mortadha Ben Ouanes', 'Tunisia'),
('Anis Ben Slimane', 'Tunisia'),
('Ismael Gharbi', 'Tunisia'),
('Rani Khedira', 'Tunisia'),
('Mohamed Hadj Mahmoud', 'Tunisia'),
('Hannibal Mejbri', 'Tunisia'),
('Ellyes Skhiri', 'Tunisia'),
('Elias Achouri', 'Tunisia'),
('Khalil Ayari', 'Tunisia'),
('Firas Chaouat', 'Tunisia'),
('Rayan Elloumi', 'Tunisia'),
('Hazem Mastouri', 'Tunisia'),
('Elias Saad', 'Tunisia'),
('Sebastian Tounekti', 'Tunisia'),
('Altay Bayindir', 'Turkiye'),
('Mert Gunok', 'Turkiye'),
('Ugurcan Cakir', 'Turkiye'),
('Abdulkerim Bardakci', 'Turkiye'),
('Caglar Soyuncu', 'Turkiye'),
('Eren Elmali', 'Turkiye'),
('Ferdi Kadioglu', 'Turkiye'),
('Merih Demiral', 'Turkiye'),
('Mert Muldur', 'Turkiye'),
('Ozan Kabak', 'Turkiye'),
('Samet Akaydin', 'Turkiye'),
('Zeki Celik', 'Turkiye'),
('Hakan Calhanoglu', 'Turkiye'),
('Ismail Yuksek', 'Turkiye'),
('Kaan Ayhan', 'Turkiye'),
('Orkun Kokcu', 'Turkiye'),
('Salih Ozcan', 'Turkiye'),
('Arda Guler', 'Turkiye'),
('Baris Alper Yilmaz', 'Turkiye'),
('Can Uzun', 'Turkiye'),
('Deniz Gul', 'Turkiye'),
('Irfan Can Kahveci', 'Turkiye'),
('Kenan Yildiz', 'Turkiye'),
('Kerem Akturkoglu', 'Turkiye'),
('Oguz Aydin', 'Turkiye'),
('Yunus Akgun', 'Turkiye'),
('Sergio Rochet', 'Uruguay'),
('Fernando Muslera', 'Uruguay'),
('Santiago Mele', 'Uruguay'),
('Guillermo Varela', 'Uruguay'),
('Ronald Araujo', 'Uruguay'),
('Jose Maria Gimenez', 'Uruguay'),
('Santiago Bueno', 'Uruguay'),
('Sebastian Caceres', 'Uruguay'),
('Mathias Olivera', 'Uruguay'),
('Joaquin Piquerez', 'Uruguay'),
('Matias Vina', 'Uruguay'),
('Maximiliano Araujo', 'Uruguay'),
('Giorgian de Arrascaeta', 'Uruguay'),
('Rodrigo Bentancur', 'Uruguay'),
('Agustin Canobbio', 'Uruguay'),
('Nicolas de la Cruz', 'Uruguay'),
('Emiliano Martinez', 'Uruguay'),
('Facundo Pellistri', 'Uruguay'),
('Brian Rodriguez', 'Uruguay'),
('Juan Manuel Sanabria', 'Uruguay'),
('Manuel Ugarte', 'Uruguay'),
('Federico Valverde', 'Uruguay'),
('Rodrigo Zalazar', 'Uruguay'),
('Rodrigo Aguirre', 'Uruguay'),
('Federico Vinas', 'Uruguay'),
('Darwin Nunez', 'Uruguay'),
('Chris Brady', 'USA'),
('Matt Freese', 'USA'),
('Matt Turner', 'USA'),
('Max Arfsten', 'USA'),
('Sergino Dest', 'USA'),
('Alex Freeman', 'USA'),
('Mark McKenzie', 'USA'),
('Tim Ream', 'USA'),
('Chris Richards', 'USA'),
('Antonee Robinson', 'USA'),
('Miles Robinson', 'USA'),
('Joe Scally', 'USA'),
('Auston Trusty', 'USA'),
('Tyler Adams', 'USA'),
('Sebastian Berhalter', 'USA'),
('Weston McKennie', 'USA'),
('Cristian Roldan', 'USA'),
('Brenden Aaronson', 'USA'),
('Christian Pulisic', 'USA'),
('Gio Reyna', 'USA'),
('Malik Tillman', 'USA'),
('Tim Weah', 'USA'),
('Alejandro Zendejas', 'USA'),
('Folarin Balogun', 'USA'),
('Ricardo Pepi', 'USA'),
('Haji Wright', 'USA'),
('Botirali Ergashev', 'Uzbekistan'),
('Abduvohid Nematov', 'Uzbekistan'),
('Utkir Yusupov', 'Uzbekistan'),
('Abdukodir Khusanov', 'Uzbekistan'),
('Khojiakbar Alijonov', 'Uzbekistan'),
('Rustamjon Ashurmatov', 'Uzbekistan'),
('Farrukh Sayfiev', 'Uzbekistan'),
('Sherzod Nasrullaev', 'Uzbekistan'),
('Umarbek Eshmuradov', 'Uzbekistan'),
('Avazbek Ulmasaliev', 'Uzbekistan'),
('Jakhongir Urozov', 'Uzbekistan'),
('Bekhruz Karimov', 'Uzbekistan'),
('Abdulla Abdullaev', 'Uzbekistan'),
('Akmal Mozgovoy', 'Uzbekistan'),
('Otabek Shukurov', 'Uzbekistan'),
('Jamshid Iskanderov', 'Uzbekistan'),
('Odiljon Hamrobekov', 'Uzbekistan'),
('Jaloliddin Masharipov', 'Uzbekistan'),
('Azizbek Ganiev', 'Uzbekistan'),
('Sherzod Esanov', 'Uzbekistan'),
('Abbosbek Fayzullaev', 'Uzbekistan'),
('Azizbek Amonov', 'Uzbekistan'),
('Eldor Shomurodov', 'Uzbekistan'),
('Igor Sergeev', 'Uzbekistan'),
('Oston Urunov', 'Uzbekistan'),
('Dostonbek Hamdamov', 'Uzbekistan');
